package main

import (
	"strings"
	"testing"
	"time"
)

func TestParseHeaders(t *testing.T) {
	got, err := parseHeaders([]string{"X-A: one", "X-B:two"})
	if err != nil {
		t.Fatalf("parseHeaders: %v", err)
	}
	if got["X-A"] != "one" || got["X-B"] != "two" {
		t.Errorf("parseHeaders = %v", got)
	}

	if _, err := parseHeaders([]string{"NoColonHere"}); err == nil || !strings.Contains(err.Error(), "bad -header") {
		t.Errorf("expected bad -header error, got %v", err)
	}
}

func TestHeaderComment(t *testing.T) {
	at := time.Date(2026, 7, 6, 15, 4, 5, 0, time.UTC)
	got := headerComment("https://shop.example.com/graphql", "v1.4.0", at)

	for _, want := range []string{
		"# Code generated by gqlschema v1.4.0",
		"DO NOT EDIT.",
		"# Endpoint:  https://shop.example.com/graphql",
		"# Generated: 2026-07-06T15:04:05Z",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("header comment missing %q, got:\n%s", want, got)
		}
	}
	// Every non-empty line is a comment, and it ends with a blank separator so the
	// SDL that follows is not glued to the last comment line.
	if !strings.HasSuffix(got, "\n\n") {
		t.Errorf("header comment should end with a blank line, got:\n%q", got)
	}
	for _, ln := range strings.Split(strings.TrimRight(got, "\n"), "\n") {
		if ln != "" && !strings.HasPrefix(ln, "#") {
			t.Errorf("non-comment line in header: %q", ln)
		}
	}

	// A non-UTC time is normalised to UTC.
	loc := time.FixedZone("PST", -8*3600)
	if utc := headerComment("x", "dev", at.In(loc)); !strings.Contains(utc, "2026-07-06T15:04:05Z") {
		t.Errorf("timestamp not normalised to UTC:\n%s", utc)
	}
}

// -out appends .graphql only when the path has no extension.
func TestOutputPath(t *testing.T) {
	cases := []struct{ in, want string }{
		{"schema", "schema.graphql"},
		{"out/admin/unstable", "out/admin/unstable.graphql"},
		{"schema.gql", "schema.gql"},
		{"schema.graphql", "schema.graphql"},
	}
	for _, c := range cases {
		if got := outputPath(c.in); got != c.want {
			t.Errorf("outputPath(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
