// Command gqlschema fetches a GraphQL schema from an endpoint via an
// introspection query and writes it out as SDL, in a form genqlient can consume.
//
// It writes a single file named by -out (default schema.graphql). Schema
// descriptions are included by default and omitted with -no-descriptions.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"time"

	"github.com/patjakubik/gqlschema"
)

// headerFlag is the repeatable -header flag.
type headerFlag []string

func (h *headerFlag) String() string { return strings.Join(*h, ", ") }
func (h *headerFlag) Set(v string) error {
	*h = append(*h, v)
	return nil
}

func main() {
	var (
		endpoint = flag.String("endpoint", "", "GraphQL endpoint URL (required)")
		out      = flag.String("out", "schema", "output path; .graphql is appended when the path has no extension")
		method   = flag.String("method", "POST", "HTTP method for the introspection request")
		noDesc   = flag.Bool("no-descriptions", false, "omit schema descriptions from the output")
		sorted   = flag.Bool("sort", false, "sort types, fields, arguments, and enum values alphabetically for stable diffs")
		fixTbl   = flag.Bool("fix-tables", false, "normalize markdown tables in descriptions so they render (blank lines around tables, short rows padded)")
		stamp    = flag.Bool("stamp", false, "prepend a header comment with the generator, version, endpoint, and timestamp")
		headers  headerFlag
	)
	flag.Var(&headers, "header", "HTTP header as 'Key: Value' (repeatable)")
	flag.Parse()

	if *endpoint == "" {
		fmt.Fprintln(os.Stderr, "error: -endpoint is required")
		flag.Usage()
		os.Exit(2)
	}

	headerMap, err := parseHeaders(headers)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(2)
	}

	sch, err := gqlschema.Fetch(context.Background(), *endpoint, &gqlschema.Options{
		Method:  *method,
		Headers: headerMap,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	if *sorted {
		sch.Sort()
	}
	if *fixTbl {
		sch.FixMarkdownTables()
	}

	banner := ""
	if *stamp {
		banner = headerComment(*endpoint, generatorVersion(), time.Now())
	}

	path := outputPath(*out)
	sdl := sch.SDL(&gqlschema.SDLOptions{OmitDescriptions: *noDesc})
	if err := writeFile(path, banner+sdl); err != nil {
		fmt.Fprintf(os.Stderr, "error writing schema: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}

// parseHeaders turns repeated 'Key: Value' flags into a header map.
func parseHeaders(headers []string) (map[string]string, error) {
	m := make(map[string]string, len(headers))
	for _, h := range headers {
		k, v, ok := strings.Cut(h, ":")
		if !ok {
			return nil, fmt.Errorf("bad -header %q, expected 'Key: Value'", h)
		}
		m[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return m, nil
}

// headerComment builds the SDL comment block prepended to output when -stamp is
// set. version and the timestamp are parameters so they can be pinned in tests.
func headerComment(endpoint, version string, generatedAt time.Time) string {
	return fmt.Sprintf(
		"# Code generated by gqlschema %s (github.com/patjakubik/gqlschema); DO NOT EDIT.\n"+
			"# Endpoint:  %s\n"+
			"# Generated: %s\n\n",
		version, endpoint, generatedAt.UTC().Format(time.RFC3339))
}

// generatorVersion reports the module version gqlschema was built at. It is set
// automatically by the Go toolchain when the tool is installed via `go install
// …@version` or pinned as a `go tool`; a local `go run .` build reports "dev".
func generatorVersion() string {
	if info, ok := debug.ReadBuildInfo(); ok {
		if v := info.Main.Version; v != "" && v != "(devel)" {
			return v
		}
	}
	return "dev"
}

// outputPath appends .graphql to -out only when it names no extension, so an
// explicit file name like schema.gql is written as given.
func outputPath(out string) string {
	if filepath.Ext(out) == "" {
		return out + ".graphql"
	}
	return out
}

func writeFile(path, content string) error {
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
